// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleDLock.Core.Persistence;

namespace SimpleDLock.Core.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleDLock.Core.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("BookedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("SimpleDLock.Core.Entities.FieldEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Field");

                    b.HasData(
                        new
                        {
                            Name = "Field 01"
                        },
                        new
                        {
                            Name = "Field 02"
                        },
                        new
                        {
                            Name = "Field 03"
                        },
                        new
                        {
                            Name = "Field 04"
                        },
                        new
                        {
                            Name = "Field 05"
                        },
                        new
                        {
                            Name = "Field 06"
                        },
                        new
                        {
                            Name = "Field 07"
                        },
                        new
                        {
                            Name = "Field 08"
                        },
                        new
                        {
                            Name = "Field 09"
                        },
                        new
                        {
                            Name = "Field 10"
                        },
                        new
                        {
                            Name = "Field 11"
                        },
                        new
                        {
                            Name = "Field 12"
                        },
                        new
                        {
                            Name = "Field 13"
                        },
                        new
                        {
                            Name = "Field 14"
                        },
                        new
                        {
                            Name = "Field 15"
                        },
                        new
                        {
                            Name = "Field 16"
                        },
                        new
                        {
                            Name = "Field 17"
                        },
                        new
                        {
                            Name = "Field 18"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
